apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-exec-rb
  namespace: observability-server
subjects:
- kind: ServiceAccount
  name: pod-list-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-list-exec
  apiGroup: rbac.authorization.k8s.io

